name: Run Discord Bot on Command Detection

on:
  schedule:
    - cron: "* * * * *"  # Runs every minute

jobs:
  check-website:
    runs-on: ubuntu-latest

    steps:
      - name: Check Command Status
        id: check_command
        run: |
          response=$(curl -s https://unnamedeveloper.github.io/bot/)
          echo "response=$response" >> $GITHUB_ENV
          if [[ "$response" == *"true"* ]]; then
            echo "command_detected=true" >> $GITHUB_ENV
          else
            echo "command_detected=false" >> $GITHUB_ENV

      - name: Start Bot if Command Detected
        if: env.command_detected == 'true'
        run: |
          echo "Starting bot..."
          node index.js &
          sleep 60  # Keep the bot running for 60 seconds

      - name: Stop Workflow if No Commands
        if: env.command_detected == 'false'
        run: echo "No commands detected. Workflow ending."
